### ISSUE TITLE
Pick a DB adapter

### ISSUE THREAD

**Issue by pathikrit** [pathikrit/-dev-null#2]
We need an adapter which can talk postgres, mysql, sqlserver and maybe even mongo, couch etc etc etc.

Some research yield these (some of these are full-fledged ORMs, but in our case, we just execute user provided queries):
https://github.com/grncdr/node-any-db
http://docs.sequelizejs.com/en/latest/docs/getting-started/
https://github.com/1602/jugglingdb
https://github.com/balderdashy/waterline

**Comment by pathikrit** [comment]
MOAR:

https://github.com/DrBenton/Node-DBI
https://github.com/strongloop/loopback-datasource-juggler
http://camintejs.com/

I am leaning towards juggler since it passes all these criteria:
1. High number of commits and Github starts
2. Still in active development
3. Must support mysql, postgres, mssql, mongo, couch, oracle 
4. Well documented: http://docs.strongloop.com/display/public/LB/Connecting+models+to+data+sources
5. Not an ORM - can execute native queries just fine..
6. Bonus! It even has a REST adapter: http://docs.strongloop.com/display/public/LB/REST+connector

**Comment by pathikrit** [comment]
@bcherny : 
What do you think of http://strongloop.com? Can we use them for the whole stack? They make juggler

They have something frighteningly similar: https://strongloop.com/node-js/arc/ (see second screenshot). But no team based sharing of APIs etc.

**Comment by bcherny** [comment]
well if they did it that's a good sign that people need it. let's make it better :)

**Comment by pathikrit** [comment]
juggler it is.
